version: '3.8'

services:
  db:
    image: postgres:14
    container_name: db_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    container_name: app_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypass@db:5432/mydb
      PORT: 4000
    expose:
      - "4000"   # 只在內網開放

  frontend:
    build: ./frontend
    container_name: app_frontend
    depends_on:
      - backend
    expose:
      - "80"     # 只在內網開放

  proxy:
    image: nginx:alpine
    container_name: web_proxy
    ports:
      - "80:80"   # 對外只暴露 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
