name: Deploy via Tailscale SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          # 如果你的 Tailnet 要求使用 tag 來授權，請加上 tags:
          # tags: tag:ci

      - name: Deploy via Tailscale SSH
        run: |
          tailscale ssh ${{ secrets.CI_CD_USERNAME }}@${{ secrets.TAILSCALE_HOST }} -- \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            "cd ~/multi-container-app && bash deploy.sh"

