name: Deploy via Tailscale SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy via Tailscale SSH
        run: |
          tailscale ssh --accept-host-key \
            ${{ secrets.CI_CD_USERNAME }}@${{ secrets.TAILSCALE_HOST }} \
            "cd ~/multi-container-app && bash deploy.sh"
