name: Deploy via Tailscale SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Tailscale
        uses: tailscale/action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy via Tailscale SSH
        run: |
          # 這裡我們直接呼叫 Tailscale SSH，不需要 SSH key/config
          tailscale ssh -o StrictHostKeyChecking=no \
            ${{ secrets.CI_CD_USERNAME }}@${{ secrets.TAILSCALE_HOST }} \
              "cd ~/multi-container-app && bash deploy.sh"
