name: Deploy on Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # 這裡指定用 self-hosted runner
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy script
        run: |
          cd ~/multi-container-app
          bash deploy.sh
